### ISSUE TITLE
Sometimes Time in the bottle crashes the server.

### ISSUE THREAD

**Issue by IdealIdeas** [alkyaly/Time-in-a-Bottle#1]
It seems if I try to use it on an active vanilla blast furnace it crashes the game and the server.

Some mods might also be changing how stable it is because after adding some new mods and going to TIB a block I usually use it on, it crashed the server when it didnt previously.

When its the 2nd case, you cant restart the server until you remove the TIB mod, because the server will get stuck trying to load the server and then crashing.

**Comment by alkyaly** [comment]
Do you have the latest.log and possibly a mod list?
I couldn't reproduce it

**Comment by IdealIdeas** [comment]
[Here is a download to all the mods currently running on my server as well as a log where I crashed the server while trying to TIB a running blast furnace. also included is the crash report.](https://www.mediafire.com/file/q94qor8mban5pkm/Mods+and+Log.rar/file)

This problem persists until I remove the mod. I can put the mod back in after I save the world without the mod.

Ive been adding more mods constantly and it appears that it has increased how often this crashes the server. As there used to be only a few blocks that TIB would crash but now its feeling like it crashes when used on any block.

**Comment by alkyaly** [comment]
I already had fixed this crash in-dev, but didn't release it.
Try with [this new version](https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle/files/3231599), if there's any other problem let me know.
Thanks for the report
