### ISSUE TITLE
[suggestion] config for max speed multiplier and max duration

### ISSUE THREAD

**Issue by milkev** [alkyaly/Time-in-a-Bottle#3]
it would be cool if there were config options for the max speed you can apply, and the duration that it applies for. It feels rather slow, imo, at the current max level.
example of what a customized config could look like, bear in mind I am unsure of what your default values are so these are just guesses:

//Speed levels of the time effect, higher tiers will consume more time
//default=[2,4,8,16,32]
speed_levels=[2,4,8,16,32,64,128]

//Duration of time effect in seconds, increasing will also increase time usage
//default=15
duration=30

**Comment by alkyaly** [comment]
Added in https://github.com/alkyaly/Time-in-a-Bottle/commit/bc5f27c89ed84567e65ddb864cf8caf9605a3451! Thanks for the suggestion.

For future references:
`speed-levels` is an array of Integers, the order of the Items in the array matter.
`duration` is the amount of seconds the AcceleratorEntity persists.
`time-second` is the amount of ticks to add to the Time in a Bottle every second.
`max-time` is the max amount of ticks a Time in a Bottle can store.
