### ISSUE TITLE
Using the bottle on wheat does not work version 1.17

### ISSUE THREAD

**Issue by tristanzwart** [alkyaly/Time-in-a-Bottle#4]

**Comment by alkyaly** [comment]
Are you sure they aren't just slower?
I think I decreased the chance of random ticks from 1.16 -> 1.17.
Will test it, thanks for the report

**Comment by tristanzwart** [comment]
If this is the case can you increase de default speed of the bottle

**Comment by alkyaly** [comment]
Just change the speed-levels values in the config ;)
